python main.py run ..\data --segment-size=20 --overlap=0
python main.py run ..\data --segment-size=20 --overlap=0.2
python main.py run ..\data --segment-size=20 --overlap=0.5
python main.py run ..\data --segment-size=50 --overlap=0
python main.py run ..\data --segment-size=50 --overlap=0.2
python main.py run ..\data --segment-size=50 --overlap=0.5
python main.py run ..\data --segment-size=100 --overlap=0
python main.py run ..\data --segment-size=100 --overlap=0.2
python main.py run ..\data --segment-size=100 --overlap=0.5
